application: learn2mine
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /admin/.*
  script: google.appengine.ext.admin.application
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /Javascript
  static_dir: Javascript

- url: /images
  static_dir: images

- url: /datasets
  static_dir: datasets

- url: /badges
  static_dir: badges

- url: /remoteapi.*
  script: google.appengine.ext.remote_api.handler.app
  login: admin

- url: /.*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
